spring:
  datasource:
    name: dataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: "jdbc:oracle:thin:@localhost:1521:XE"
    username: system
    password: root
#    url: "jdbc:oracle:thin:@10.137.122.1:1521:eflexdb"
#    username: eflex
#    password: eflex
    max-active: 100
    initial-size: 2
    min-idle: 2
    max-idle: 10
    test-while-idle: true
    test-on-borrow: true
    validation-query: "select  1 from dual"
    initialize: false
  batch:
    job:
      enabled: false
server:
  port: 8082
